### ISSUE TITLE
Did not work on every site I tried

### ISSUE THREAD

**Issue by TharathielCB** [GooglyBlox/ClipboardToFileInput#1]
Hi, I just saw your extension, and this is what I was looking for for a very long time.

Sadly it won't work for me. 
I installed it as described
![Screenshot 2023-11-16 175725](https://github.com/GooglyBlox/ClipboardToFileInput/assets/99963785/0b207fa7-486b-4a37-847a-ef3f0967d2cb)
![Screenshot 2023-11-16 175835](https://github.com/GooglyBlox/ClipboardToFileInput/assets/99963785/429ebd56-4b34-4796-88e7-cb93cea430a2)

But if I open a Website like wetransfer.com I can't attach the files I have in my clipboard.

What am I doing wrong?

**Comment by GooglyBlox** [comment]
Hello! 

It looks like there are some custom file input fields that I didn't prepare for, let me quickly work on a solution for handling those 😄

**Comment by TharathielCB** [comment]
This would be awesome. And could you propably upload a GIF that shows a little bit more? I'd like to see how the window looks like when it opens up :D

**Comment by GooglyBlox** [comment]
Alright, I spent a while working on the [latest release](https://github.com/GooglyBlox/ClipboardToFileInput/releases/tag/v2) - please let me know if you're still encountering issues! It should be much more intuitive to use.

**Comment by TharathielCB** [comment]
AH perfect. Thank you very much. I tried it on a few websites like ebay, wetransfer, github an so on and it worked! I will come back to you if I encouter any problems :D

**Comment by GooglyBlox** [comment]
Fantastic to hear! I'll close this issue for now, but if you ever run into issues with it again please open another issue and I'll work to fix it as fast as I can 😄
