### ISSUE TITLE
When using the extension in an Incognito window, it redirects you to a normal window

### ISSUE THREAD

**Issue by minnieoo** [GooglyBlox/ClipboardToFileInput#10]
It still functions as expected, and the pop up is there in the Incognito window, but it is a little inconvenient how it redirects you and you have to go back to your Incognito window., it's not a functional issue but more like a QOL thing

**Comment by GooglyBlox** [comment]
Woah, silly! I've never considered how it works in incognito mode, and I can replicate the issue. Let me quickly write up a fix 😄

**Comment by GooglyBlox** [comment]
Should be resolved in the [latest release!](https://github.com/GooglyBlox/ClipboardToFileInput/releases/tag/v2.8)

**Comment by minnieoo** [comment]
you're the best :D
