### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by gakselrod** [GooglyBlox/ClipboardToFileInput#11]
Every month I have to file ~100 expenses with Expensify and printing email and web receipts to PDF and then manually uploading each takes forever. I wished for an extension to let me paste screen grabs into their file upload box and found your extension. I've been using v2.3 for a long time (I think I found it somewhere else on the internet) and was hitting the issue where it would always open the "nothing on your clipboard" tab on the first try, but then I found the project on github and was thrilled to see you've been actively improving it. Just wanted to drop a note to say THANK YOU!!!

**Comment by GooglyBlox** [comment]
Thank you so much for the kind words!! It means the world to me that people are actually benefitting from this silly project I made on a whim. ❤️

**Comment by gakselrod** [comment]
I just thought of a feature request to reduce clicks. If I have an image on my clipboard and I ctrl+v onto a page that has a file input on screen, go ahead and paste it in. 

If you don't want to make that the default behavior in case people are worried about accidentally pasting stuff to places they don't want, perhaps you could enable it on a per-site basis. E.g. the first time I do it, show the normal popup that appears if I click on the file input and have a checkbox "auto-input pastes on this site"

**Comment by GooglyBlox** [comment]
Great idea! I quickly wrote this possible release candidate for v2.9 with that feature, I'd love it if you could give it a test run and see if it works for your use cases. 😄 

If it does, I'll make some more small adjustments and release it as the main release.

https://www.mediafire.com/file/326lfa0ka4s4l7g/ClipboardToFileInput.zip/file

**Comment by gakselrod** [comment]
That was fast!! Just tested it on Expensify - worked like a charm!

**Comment by GooglyBlox** [comment]
Super glad to hear it! I'll work on a few other small changes before releasing the main v2.9 release. I'll close this issue now, but thank you again so much for the kind words! It genuinely makes my week.

If you have any other ideas, suggestions, or bug reports for this extension in the future, feel free to open another issue!
