### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by phamduyphat** [GooglyBlox/ClipboardToFileInput#15]
When on youtube.com, youtube's ui gets laggier the longer you use the site. Refreshes will help with the performance a little bit, but it's already worse right when i enable the extension.

list of all extensions
![image](https://github.com/user-attachments/assets/5f7bf3ca-fe3f-429c-8b03-af48d5ecc1cd)

**Comment by GooglyBlox** [comment]
Uh oh, that's not good! Let's see if we can fix this with some optimizations. If not, I'll see if my extension could potentially be clashing with another of yours. I couldn't notice any performance degradation on YouTube during my testing (although I could just not be waiting long enough to see significant issues). I tested it on Brave version 1.67.134 with Chromium version 126.0.6478.186, if you're using Google Chrome or another Chromium-based browser like Edge that'd be helpful to know too.

I made a few small changes to how I handle my MutationObservers, would you be able to test the below 3.1 RC and see if you're still experiencing performance issues, it'd be greatly appreciated!
https://www.mediafire.com/file/c06uk9lc6g53urq/ClipboardToFileInput.zip/file

**Comment by phamduyphat** [comment]
the initial issue was tested on Brave [Version 1.67.134 Chromium: 126.0.6478.186. After posting the issue I decided to disable all extensions except for yours and try to pinpoint any conflicting extensions, seems like it only interferes with premid
the test extension you uploaded seems to not lag at all! 
literally using right now with no issue👍
