### ISSUE TITLE
"Failed to load extension"

### ISSUE THREAD

**Issue by minnieoo** [GooglyBlox/ClipboardToFileInput#3]
trying to load into extensions. i unzipped it and click `load unpacked` and it gives me this error
![image](https://github.com/GooglyBlox/ClipboardToFileInput/assets/137783738/f5412be7-80b2-449f-ac3f-92c4b6a37110)

i noticed a lot of files are missing when i look inside from the popup after clicking `load unpacked`, files that are there if i look in regular file explorer

**Comment by minnieoo** [comment]
EDIT: nvm i was doing it wrong i guess? i dragged and dropped `ClipboardToFileInput-main\ClipboardToFileInput-main` onto the screen and it worked

**Comment by GooglyBlox** [comment]
Okay good to hear it worked! If you have any further issues, feel free to create another issue. 😄

**Comment by minnieoo** [comment]
this extension literally saved my life btw. you're a god send. im showing it to everyone i know
