### ISSUE TITLE
'your file couldn't be accessed' redirect whenever i browse files on computer, but the file uploads normally

### ISSUE THREAD

**Issue by minnieoo** [GooglyBlox/ClipboardToFileInput#5]
i'm redirected here whenever i use 'browse files', though the file uploads normally. it's quite inconvenient, not sure why it's happening. chrome & win11. also, thanks to the dev! i've been looking for something like this for over a year :D 
![image](https://github.com/GooglyBlox/ClipboardToFileInput/assets/137783738/bbbf3c1f-9a80-4ab9-a9d3-db2a415e2593)

**Comment by GooglyBlox** [comment]
Hello! Using w10 + chrome and I can't replicate :(

Next time it happens, could you by chance open the developer tools console and see if anything was printed in the logs? It'd be extremely helpful! 

Glad this silly little project could be of help :)

**Comment by GooglyBlox** [comment]
I've genuinely tried everything to replicate this issue. I'm hoping one of the updates since then (there's been 5!) fixed it. If it happens again, please let me know and I'll re-open the issue and keep testing!
