### ISSUE TITLE
ANNOYING REDIRECT

### ISSUE THREAD

**Issue by minnieoo** [GooglyBlox/ClipboardToFileInput#9]
PLEASE REMOVE THIS ANNOYING REDIRECT. I really love this extension though 💗
![image](https://github.com/GooglyBlox/ClipboardToFileInput/assets/137783738/29974f50-77d2-44ec-990d-e9cdfb6d9651)

**Comment by GooglyBlox** [comment]
Hello! There are a few reasons that redirect might appear for longer than a few milliseconds:

1. You copied an invalid file to your clipboard (something that the extension isn't prepared to handle, like an exe)
2. You don't have anything in your clipboard
3. Something is going wrong with the extension

If possible, would you be able to provide:
- The file type you're trying to paste
- The websites you're trying to paste on

**Comment by minnieoo** [comment]
The redirect itself is extremely annoying and inconvenient, if i don't have anything in my clipboard, that's fine and intentional, and i am just trying to access my files without being redirected 5 times. i was trying to upload personal files to artstation with nothing in the clipboard. since this extension pops up whether you have anything in your clipboard or not, it's the only way to access your files with the extension enabled. that's why the redirect is so annoying. The extension is working as expected so no worries there, it's a great and useful extension!! I just think the redirect is a really annoying thing that made me consider just turning it off

**Comment by GooglyBlox** [comment]
Oh, I gotcha! Hadn't even thought of that. I'll work on a release that doesn't persist the helper tab when there's nothing in your clipboard 😄

**Comment by minnieoo** [comment]
Thank you so much! And thank you very much for creating this amazing extension, I share it to everybody I know. This was the solution to the hunt for an alternative to opera's easy files and it works wonderfully 💗💗💗

**Comment by GooglyBlox** [comment]
Should be fixed in the latest version!

**Comment by minnieoo** [comment]
so much better!! thank you for your time and effort, its much appreciated!! 💗
